-- Create JSONB domain for PostgreSQL compatibility
CREATE DOMAIN IF NOT EXISTS JSONB AS OTHER;

-- Create sequences with explicit schema
CREATE SEQUENCE IF NOT EXISTS PUBLIC.employee_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS PUBLIC.seat_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS PUBLIC.office_room_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS PUBLIC.floor_seq START WITH 1 INCREMENT BY 1;

-- Create tables with proper sequence defaults
CREATE TABLE IF NOT EXISTS employees (
    id BIGINT GENERATED BY DEFAULT AS SEQUENCE PUBLIC.employee_seq PRIMARY KEY,
    created_at TIMESTAMP,
    full_name VARCHAR(255),
    occupation VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS floors (
    id BIGINT GENERATED BY DEFAULT AS SEQUENCE PUBLIC.floor_seq PRIMARY KEY,
    created_at TIMESTAMP,
    floor_number INTEGER,
    name VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS office_rooms (
    id BIGINT GENERATED BY DEFAULT AS SEQUENCE PUBLIC.office_room_seq PRIMARY KEY,
    created_at TIMESTAMP,
    name VARCHAR(255),
    room_number VARCHAR(255),
    floor_id BIGINT REFERENCES floors(id)
);

CREATE TABLE IF NOT EXISTS seats (
    id BIGINT GENERATED BY DEFAULT AS SEQUENCE PUBLIC.seat_seq PRIMARY KEY,
    created_at TIMESTAMP,
    seat_number VARCHAR(255),
    employee_id BIGINT REFERENCES employees(id),
    room_id BIGINT REFERENCES office_rooms(id)
); 